language: objective-c
osx_image: xcode11.3
xcode_workspace: TheCodeBlog.xcworkspace
xcode_scheme: TheCodeBlog
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 11
cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

install:
# Grab the latest Danger JS from npm
- npm install -g danger
# Compile the Danger runtime
- swift build

script:
# Run the Dangerfile.swift
- swift run danger-swift ci
# Test my app...
# - [your other commands]